#!/bin/bash
set -e
set -x

usage()
{
    echo "Usage: $0 <build | clippy | flash>"
    exit 1
}

tgt="thumbv7em-none-eabihf"
chip="STM32F411CEUx"

flags="--release --target $tgt"
case "$1" in
b*)
    set -x
    cargo build $flags
    ;;
c*)
    set -x
    cargo clippy $flags
    ;;
f*)
    set -x
    cargo flash $flags --chip $chip
    ;;
*)
    usage
    ;;
esac
exit 0
# EOF
